// <auto-generated />
using System;
using BorrowingsService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BorrowingsService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220118193653_required_borrowing_data")]
    partial class required_borrowing_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BorrowingsService.Models.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FromData")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ToData")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Borrowings");
                });
#pragma warning restore 612, 618
        }
    }
}
